apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-py-deploy
  labels:
    app: app-py-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-py-test
  template:
    metadata:
      labels:
        app: app-py-test
    spec:
      containers:
      - name: flask-app
        image: disizwil365/mon-app-devsecops:v7
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-py-test-service
spec:
  selector:
    app: app-py-test
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
