apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-py-deploy
  labels:
    app: app-py-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-py-test
  template:
    metadata:
      labels:
        app: app-py-test
    spec:
      containers:
      - name: flask-app
        image: disizwil365/mon-app-devsecops:latest # Ton image sur Docker Hub
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mon-app-service
spec:
  selector:
    app: app-py-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer